spring:
  application.name: spring-rest-forge
  data.rest.basePath: /data

server:
  port: 8080
  contextPath: /

logging:
  # Uncomment file to enable file logging
#  file: app.log
  level:
    com.github.apycazo: DEBUG

spring-rest-forge:
  customH2:
    enable: false
    embedded: true
    generateDdl: true
    url: jdbc:h2:file:./h2db
    scan: com.github.apycazo
  gateway:
    enable: false
    mapping: gateway
    origin: '*'
  heartbeat.enable: false
  registerInterceptors.enable: false